# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131313)
$foreground = rgb(F7F7F7)
$color0 = rgb(3B3B3B)
$color1 = rgb(6D932E)
$color2 = rgb(6E962E)
$color3 = rgb(6C9630)
$color4 = rgb(8CA369)
$color5 = rgb(A7A7A7)
$color6 = rgb(AEAEAE)
$color7 = rgb(EBEBEB)
$color8 = rgb(A5A5A5)
$color9 = rgb(91C43D)
$color10 = rgb(93C73D)
$color11 = rgb(90C840)
$color12 = rgb(BBD98C)
$color13 = rgb(DFDFDF)
$color14 = rgb(E8E8E8)
$color15 = rgb(EBEBEB)
